import type { ChangeEvent, ComponentType, KeyboardEvent, MutableRefObject } from 'react';
import type { ConversationDto, ChatMessageDto } from '@/features/chat/application/actions';
import type { VoiceRecordingResult } from '@/features/chat/application/useVoiceRecorder';

export interface ChatRoomViewProps {
  actionMenuRef: MutableRefObject<HTMLDivElement | null>;
  awaitingCompleteResponse: boolean;
  canCancelPending: boolean;
  canReaderAcceptReject: boolean;
  canShowInput: boolean;
  canStartNewSession: boolean;
  canUseActionMenu: boolean;
  conversation: ConversationDto | null;
  currentUserId: string;
  disputeReason: string;
  hasMore: boolean;
  headerWarning: boolean;
  imageInputRef: MutableRefObject<HTMLInputElement | null>;
  inputPlaceholder: string;
  inputRef: MutableRefObject<HTMLInputElement | null>;
  isReadOnly: boolean;
  isUserRole: boolean | null;
  loading: boolean;
  loadingMore: boolean;
  locale: string;
  messages: ChatMessageDto[];
  messagesEndRef: MutableRefObject<HTMLDivElement | null>;
  newMessage: string;
  offerResponseMap: Record<string, 'accept' | 'reject'>;
  otherAvatar: string | null;
  otherName: string;
  processingAction: string | null;
  processingOfferId: string | null;
  readOnlyHint: string;
  readerStatus: { text: string; color: string };
  rejectReason: string;
  remoteTyping: boolean;
  requestingAddMoney: boolean;
  scrollRef: MutableRefObject<HTMLDivElement | null>;
  sending: boolean;
  showActionMenu: boolean;
  showDisputeModal: boolean;
  showPaymentOffer: boolean;
  startingNewSession: boolean;
  title: string;
  uploadingMedia: boolean;
  uploadPercent: number;
  uploadingMediaLabel: string;
  warningText: string;
  PaymentOfferModal: ComponentType<{
    onClose: () => void;
    onSubmit: (amount: number, note: string) => Promise<void>;
  }>;
  VoiceMessageBubble: ComponentType<{
    audioUrl: string;
    durationMs?: number | null;
    isMe: boolean;
  }>;
  VoiceRecorderButton: ComponentType<{
    disabled?: boolean;
    onRecordingComplete: (result: VoiceRecordingResult) => void;
  }>;
  onAcceptConversation: () => Promise<void>;
  onAcceptOffer: (message: ChatMessageDto) => Promise<boolean>;
  onBack: () => void;
  onCancelPending: () => Promise<void>;
  onCloseDisputeModal: () => void;
  onClosePaymentOffer: () => void;
  onImageInputChange: (event: ChangeEvent<HTMLInputElement>) => Promise<void>;
  onInputChange: (value: string) => void;
  onInputKeyDown: (event: KeyboardEvent<HTMLInputElement>) => void;
  onLoadMore: () => Promise<void>;
  onRejectConversation: () => Promise<void>;
  onRejectOffer: (message: ChatMessageDto) => Promise<boolean>;
  onRequestComplete: () => Promise<void>;
  onRespondComplete: (accept: boolean) => Promise<void>;
  onSendPaymentOffer: (amount: number, note: string) => Promise<boolean>;
  onSendTextMessage: () => Promise<boolean>;
  onSetDisputeReason: (value: string) => void;
  onSetRejectReason: (value: string) => void;
  onSetShowActionMenu: (value: boolean) => void;
  onSetShowDisputeModal: (value: boolean) => void;
  onSetShowPaymentOffer: (value: boolean) => void;
  onStartNewSession: () => Promise<void>;
  onSubmitDispute: () => Promise<void>;
  onVoiceRecordingComplete: (result: VoiceRecordingResult) => Promise<void>;
}
