sonar.sources=Backend/src,Frontend/src
sonar.tests=Backend/tests,Frontend/tests
sonar.exclusions=**/bin/**,**/obj/**,Frontend/.next/**,**/node_modules/**,**/*.min.js
sonar.coverage.exclusions=**/Program.cs,**/Migrations/**
