export const PROTECTED_PREFIXES = [
 '/profile',
 '/wallet',
 '/chat',
 '/collection',
 '/reading',
 '/reader',
 '/readers',
 '/gamification',
 '/leaderboard',
 '/gacha',
 '/inventory',
 '/community',
 '/premium',
 '/notifications',
 '/admin',
] as const;
