// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TarotNow.Infrastructure.Persistence;

#nullable disable

namespace TarotNow.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260415153728_RemovePremiumSubscriptionFeature")]
    partial class RemovePremiumSubscriptionFeature
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TarotNow.Domain.Entities.AiRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ChargeDiamond")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("charge_diamond");

                    b.Property<long>("ChargeGold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("charge_gold");

                    b.Property<DateTimeOffset?>("CompletionMarkerAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completion_marker_at");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FallbackReason")
                        .HasColumnType("text")
                        .HasColumnName("fallback_reason");

                    b.Property<string>("FinishReason")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("finish_reason");

                    b.Property<DateTimeOffset?>("FirstTokenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_token_at");

                    b.Property<short?>("FollowupSequence")
                        .HasColumnType("smallint")
                        .HasColumnName("followup_sequence");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("PolicyVersion")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("policy_version");

                    b.Property<string>("PromptVersion")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("prompt_version");

                    b.Property<string>("ReadingSessionRef")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("reading_session_ref");

                    b.Property<string>("RequestedLocale")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("requested_locale");

                    b.Property<short>("RetryCount")
                        .HasColumnType("smallint")
                        .HasColumnName("retry_count");

                    b.Property<string>("ReturnedLocale")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("returned_locale");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("requested")
                        .HasColumnName("status");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("trace_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_ai_requests");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("idx_ai_requests_idempotency")
                        .HasFilter("idempotency_key IS NOT NULL");

                    b.HasIndex("ReadingSessionRef")
                        .HasDatabaseName("idx_ai_requests_reading");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_ai_requests_user_id");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("idx_ai_requests_status");

                    b.ToTable("ai_requests", (string)null);
                });

            modelBuilder.Entity("TarotNow.Domain.Entities.AuthSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("device_id");

                    b.Property<string>("LastIpHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("last_ip_hash");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at_utc");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("UserAgentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("user_agent_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_auth_sessions");

                    b.HasIndex("RevokedAtUtc")
                        .HasDatabaseName("ix_auth_sessions_revoked_at_utc");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_auth_sessions_user_id");

                    b.HasIndex("UserId", "DeviceId")
                        .IsUnique()
                        .HasDatabaseName("ix_auth_sessions_user_id_device_id_active")
                        .HasFilter("\"revoked_at_utc\" IS NULL");

                    b.ToTable("auth_sessions", (string)null);
                });

            modelBuilder.Entity("TarotNow.Domain.Entities.ChatFinanceSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConversationRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("conversation_ref");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ReaderId")
                        .HasColumnType("uuid")
                        .HasColumnName("reader_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<long>("TotalFrozen")
                        .HasColumnType("bigint")
                        .HasColumnName("total_frozen");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_chat_finance_sessions");

                    b.HasIndex("ConversationRef")
                        .IsUnique()
                        .HasDatabaseName("ix_chat_finance_sessions_conversation_ref");

                    b.ToTable("chat_finance_sessions", (string)null);
                });

            modelBuilder.Entity("TarotNow.Domain.Entities.ChatQuestionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<long>("AmountDiamond")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_diamond");

                    b.Property<DateTime?>("AutoRefundAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("auto_refund_at");

                    b.Property<DateTime?>("AutoReleaseAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("auto_release_at");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<string>("ConversationRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("conversation_ref");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DisputeWindowEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dispute_window_end");

                    b.Property<DateTime?>("DisputeWindowStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dispute_window_start");

                    b.Property<Guid>("FinanceSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("finance_session_id");

                    b.Property<string>("IdempotencyKey")
                        .HasColumnType("text")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTime?>("OfferExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("offer_expires_at");

                    b.Property<Guid>("PayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("payer_id");

                    b.Property<string>("ProposalMessageRef")
                        .HasColumnType("text")
                        .HasColumnName("proposal_message_ref");

                    b.Property<DateTime?>("ReaderResponseDueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reader_response_due_at");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uuid")
                        .HasColumnName("receiver_id");

                    b.Property<DateTime?>("RefundedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refunded_at");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at");

                    b.Property<DateTime?>("RepliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("replied_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_chat_question_items");

                    b.HasIndex("FinanceSessionId")
                        .HasDatabaseName("ix_chat_question_items_finance_session_id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_chat_question_items_idempotency_key")
                        .HasFilter("idempotency_key IS NOT NULL");

                    b.ToTable("chat_question_items", (string)null);
                });

            modelBuilder.Entity("TarotNow.Domain.Entities.DepositOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AmountVnd")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_vnd");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("DiamondAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("diamond_amount");

                    b.Property<string>("FxSnapshot")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("fx_snapshot");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("transaction_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_deposit_orders");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_deposit_orders_status");

                    b.HasIndex("TransactionId")
                        .IsUnique()
                        .HasDatabaseName("ix_deposit_orders_transaction_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_deposit_orders_user_id");

                    b.ToTable("deposit_orders", (string)null);
                });

            modelBuilder.Entity("TarotNow.Domain.Entities.DepositPromotion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("BonusDiamond")
                        .HasColumnType("bigint")
                        .HasColumnName("bonus_diamond");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<long>("MinAmountVnd")
                        .HasColumnType("bigint")
                        .HasColumnName("min_amount_vnd");

                    b.HasKey("Id")
                        .HasName("pk_deposit_promotions");

                    b.HasIndex("MinAmountVnd")
                        .HasDatabaseName("ix_deposit_promotions_min_amount_vnd");

                    b.ToTable("deposit_promotions", (string)null);
                });

            modelBuilder.Entity("TarotNow.Domain.Entities.EmailOtp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("otp_code");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_email_otps");

                    b.HasIndex("UserId", "Type", "IsUsed", "ExpiresAt")
                        .HasDatabaseName("ix_email_otps_user_id_type_is_used_expires_at");

                    b.ToTable("email_otps", (string)null);
                });

            modelBuilder.Entity("TarotNow.Domain.Entities.FreeDrawCredit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AvailableCount")
                        .HasColumnType("integer")
                        .HasColumnName("available_count");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_free_draw_credits");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_free_draw_credits_user_id");

                    b.ToTable("free_draw_credits", null, t =>
                        {
                            t.HasCheckConstraint("ck_free_draw_credits_available_count", "\"available_count\" >= 0");
                        });
                });

            modelBuilder.Entity("TarotNow.Domain.Entities.GachaHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("PityAfter")
                        .HasColumnType("integer")
                        .HasColumnName("pity_after");

                    b.Property<int>("PityBefore")
                        .HasColumnType("integer")
                        .HasColumnName("pity_before");

                    b.Property<string>("PoolCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("pool_code");

                    b.Property<Guid>("PoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("pool_id");

                    b.Property<int>("PullCount")
                        .HasColumnType("integer")
                        .HasColumnName("pull_count");

                    b.Property<Guid>("PullOperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("pull_operation_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<bool>("WasPityReset")
                        .HasColumnType("boolean")
                        .HasColumnName("was_pity_reset");

                    b.HasKey("Id")
                        .HasName("pk_gacha_history_entries");

                    b.HasIndex("PullOperationId")
                        .IsUnique()
                        .HasDatabaseName("ix_gacha_history_entries_pull_operation_id");

                    b.HasIndex("UserId", "CreatedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_gacha_history_entries_user_id_created_at_utc");

                    b.HasIndex("UserId", "PoolId", "CreatedAtUtc")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_gacha_history_entries_user_id_pool_id_created_at_utc");

                    b.ToTable("gacha_history_entries", null, t =>
                        {
                            t.HasCheckConstraint("ck_gacha_history_entries_pity_after_non_negative", "\"pity_after\" >= 0");

                            t.HasCheckConstraint("ck_gacha_history_entries_pity_before_non_negative", "\"pity_before\" >= 0");

                            t.HasCheckConstraint("ck_gacha_history_entries_pull_count_positive", "\"pull_count\" > 0");
                        });
                });

            modelBuilder.Entity("TarotNow.Domain.Entities.GachaPool", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<long>("CostAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("cost_amount");

                    b.Property<string>("CostCurrency")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("cost_currency");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description_en");

                    b.Property<string>("DescriptionVi")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description_vi");

                    b.Property<string>("DescriptionZh")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description_zh");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_to");

                    b.Property<int>("HardPityCount")
                        .HasColumnType("integer")
                        .HasColumnName("hard_pity_count");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name_en");

                    b.Property<string>("NameVi")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name_vi");

                    b.Property<string>("NameZh")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name_zh");

                    b.Property<string>("OddsVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("odds_version");

                    b.Property<bool>("PityEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("pity_enabled");

                    b.Property<string>("PoolType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("pool_type");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_gacha_pools");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_gacha_pools_code");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_gacha_pools_is_active");

                    b.HasIndex("EffectiveFrom", "EffectiveTo")
                        .HasDatabaseName("ix_gacha_pools_effective_from_effective_to");

                    b.ToTable("gacha_pools", null, t =>
                        {
                            t.HasCheckConstraint("ck_gacha_pools_cost_amount_positive", "\"cost_amount\" > 0");

                            t.HasCheckConstraint("ck_gacha_pools_hard_pity_non_negative", "\"hard_pity_count\" >= 0");

                            t.HasCheckConstraint("ck_gacha_pools_hard_pity_when_enabled", "(\"pity_enabled\" = false AND \"hard_pity_count\" = 0) OR (\"pity_enabled\" = true AND \"hard_pity_count\" > 0)");
                        });
                });

            modelBuilder.Entity("TarotNow.Domain.Entities.GachaPoolRewardRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long?>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<string>("Currency")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("currency");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("icon_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid?>("ItemDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_definition_id");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name_en");

                    b.Property<string>("NameVi")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name_vi");

                    b.Property<string>("NameZh")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name_zh");

                    b.Property<Guid>("PoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("pool_id");

                    b.Property<int>("ProbabilityBasisPoints")
                        .HasColumnType("integer")
                        .HasColumnName("probability_basis_points");

                    b.Property<int>("QuantityGranted")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_granted");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("rarity");

                    b.Property<string>("RewardKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("reward_kind");

                    b.HasKey("Id")
                        .HasName("pk_gacha_pool_reward_rates");

                    b.HasIndex("PoolId", "IsActive")
                        .HasDatabaseName("ix_gacha_pool_reward_rates_pool_id_is_active");

                    b.HasIndex("PoolId", "Rarity")
                        .HasDatabaseName("ix_gacha_pool_reward_rates_pool_id_rarity");

                    b.ToTable("gacha_pool_reward_rates", null, t =>
                        {
                            t.HasCheckConstraint("ck_gacha_pool_reward_rates_kind_currency", "\"reward_kind\" <> 'currency' OR (\"item_definition_id\" IS NULL AND \"currency\" IS NOT NULL AND \"amount\" > 0)");

                            t.HasCheckConstraint("ck_gacha_pool_reward_rates_kind_item", "\"reward_kind\" <> 'item' OR (\"item_definition_id\" IS NOT NULL AND \"currency\" IS NULL AND \"amount\" IS NULL)");

                            t.HasCheckConstraint("ck_gacha_pool_reward_rates_probability_positive", "\"probability_basis_points\" > 0");

                            t.HasCheckConstraint("ck_gacha_pool_reward_rates_quantity_positive", "\"quantity_granted\" > 0");
                        });
                });

            modelBuilder.Entity("TarotNow.Domain.Entities.GachaPullOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("CurrentPityCount")
                        .HasColumnType("integer")
                        .HasColumnName("current_pity_count");

                    b.Property<int>("HardPityThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("hard_pity_threshold");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed");

                    b.Property<Guid>("PoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("pool_id");

                    b.Property<int>("PullCount")
                        .HasColumnType("integer")
                        .HasColumnName("pull_count");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<bool>("WasPityTriggered")
                        .HasColumnType("boolean")
                        .HasColumnName("was_pity_triggered");

                    b.HasKey("Id")
                        .HasName("pk_gacha_pull_operations");

                    b.HasIndex("UserId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_gacha_pull_operations_user_id_idempotency_key");

                    b.HasIndex("UserId", "PoolId", "CreatedAtUtc")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_gacha_pull_operations_user_id_pool_id_created_at_utc");

                    b.ToTable("gacha_pull_operations", null, t =>
                        {
                            t.HasCheckConstraint("ck_gacha_pull_operations_current_pity_non_negative", "\"current_pity_count\" >= 0");

                            t.HasCheckConstraint("ck_gacha_pull_operations_hard_pity_non_negative", "\"hard_pity_threshold\" >= 0");

                            t.HasCheckConstraint("ck_gacha_pull_operations_pull_count_positive", "\"pull_count\" > 0");
                        });
                });

            modelBuilder.Entity("TarotNow.Domain.Entities.GachaPullRewardLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long?>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("currency");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("icon_url");

                    b.Property<bool>("IsHardPityReward")
                        .HasColumnType("boolean")
                        .HasColumnName("is_hard_pity_reward");

                    b.Property<string>("ItemCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("item_code");

                    b.Property<Guid?>("ItemDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_definition_id");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name_en");

                    b.Property<string>("NameVi")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name_vi");

                    b.Property<string>("NameZh")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name_zh");

                    b.Property<int>("PityCountAtReward")
                        .HasColumnType("integer")
                        .HasColumnName("pity_count_at_reward");

                    b.Property<string>("PoolCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("pool_code");

                    b.Property<Guid>("PoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("pool_id");

                    b.Property<Guid>("PullOperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("pull_operation_id");

                    b.Property<int>("QuantityGranted")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_granted");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("rarity");

                    b.Property<string>("RewardKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("reward_kind");

                    b.Property<Guid>("RewardRateId")
                        .HasColumnType("uuid")
                        .HasColumnName("reward_rate_id");

                    b.Property<string>("RngSeed")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("rng_seed");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_gacha_pull_reward_logs");

                    b.HasIndex("PullOperationId")
                        .HasDatabaseName("ix_gacha_pull_reward_logs_pull_operation_id");

                    b.HasIndex("UserId", "PoolId", "CreatedAtUtc")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_gacha_pull_reward_logs_user_id_pool_id_created_at_utc");

                    b.HasIndex("UserId", "PoolId", "Rarity", "CreatedAtUtc")
                        .IsDescending(false, false, false, true)
                        .HasDatabaseName("ix_gacha_pull_reward_logs_user_id_pool_id_rarity_created_at_utc");

                    b.ToTable("gacha_pull_reward_logs", null, t =>
                        {
                            t.HasCheckConstraint("ck_gacha_pull_reward_logs_kind_currency", "\"reward_kind\" <> 'currency' OR (\"item_definition_id\" IS NULL AND \"item_code\" IS NULL AND \"currency\" IS NOT NULL AND \"amount\" > 0)");

                            t.HasCheckConstraint("ck_gacha_pull_reward_logs_kind_item", "\"reward_kind\" <> 'item' OR (\"item_definition_id\" IS NOT NULL AND \"item_code\" IS NOT NULL AND \"currency\" IS NULL AND \"amount\" IS NULL)");

                            t.HasCheckConstraint("ck_gacha_pull_reward_logs_pity_non_negative", "\"pity_count_at_reward\" >= 0");

                            t.HasCheckConstraint("ck_gacha_pull_reward_logs_quantity_positive", "\"quantity_granted\" > 0");
                        });
                });

            modelBuilder.Entity("TarotNow.Domain.Entities.InventoryItemUseOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("item_code");

                    b.Property<DateTime>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<int?>("TargetCardId")
                        .HasColumnType("integer")
                        .HasColumnName("target_card_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_inventory_item_use_operations");

                    b.HasIndex("UserId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_inventory_item_use_operations_user_id_idempotency_key");

                    b.HasIndex("UserId", "ProcessedAtUtc")
                        .HasDatabaseName("ix_inventory_item_use_operations_user_id_processed_at_utc");

                    b.ToTable("inventory_item_use_operations", (string)null);
                });

            modelBuilder.Entity("TarotNow.Domain.Entities.InventoryLuckEffect", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<int>("LuckValue")
                        .HasColumnType("integer")
                        .HasColumnName("luck_value");

                    b.Property<string>("SourceItemCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_item_code");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_inventory_luck_effects");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("ix_inventory_luck_effects_expires_at_utc");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_inventory_luck_effects_user_id");

                    b.ToTable("inventory_luck_effects", null, t =>
                        {
                            t.HasCheckConstraint("ck_inventory_luck_effects_luck_value", "\"luck_value\" > 0");
                        });
                });

            modelBuilder.Entity("TarotNow.Domain.Entities.ItemDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description_en");

                    b.Property<string>("DescriptionVi")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description_vi");

                    b.Property<string>("DescriptionZh")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description_zh");

                    b.Property<int>("EffectValue")
                        .HasColumnType("integer")
                        .HasColumnName("effect_value");

                    b.Property<string>("EnhancementType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("enhancement_type");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("icon_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsConsumable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_consumable");

                    b.Property<bool>("IsPermanent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_permanent");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_en");

                    b.Property<string>("NameVi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_vi");

                    b.Property<string>("NameZh")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_zh");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("rarity");

                    b.Property<decimal>("SuccessRatePercent")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("success_rate_percent");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_item_definitions");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_item_definitions_code");

                    b.HasIndex("Type", "IsActive")
                        .HasDatabaseName("ix_item_definitions_type_is_active");

                    b.ToTable("item_definitions", null, t =>
                        {
                            t.HasCheckConstraint("ck_item_definitions_consumable_permanent_xor", "\"is_consumable\" <> \"is_permanent\"");

                            t.HasCheckConstraint("ck_item_definitions_effect_value_positive", "\"effect_value\" > 0");

                            t.HasCheckConstraint("ck_item_definitions_success_rate_percent", "\"success_rate_percent\" >= 0 AND \"success_rate_percent\" <= 100");
                        });
                });

            modelBuilder.Entity("TarotNow.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedByIp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by_ip");

                    b.Property<string>("CreatedDeviceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("created_device_id");

                    b.Property<string>("CreatedUserAgentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("created_user_agent_hash");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("LastRotateIdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("last_rotate_idempotency_key");

                    b.Property<Guid?>("ParentTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_token_id");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<string>("RevocationReason")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("revocation_reason");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_refresh_tokens_family_id");

                    b.HasIndex("ParentTokenId")
                        .HasDatabaseName("ix_refresh_tokens_parent_token_id");

                    b.HasIndex("ReplacedByTokenId")
                        .HasDatabaseName("ix_refresh_tokens_replaced_by_token_id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_refresh_tokens_session_id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token");

                    b.HasIndex("UsedAtUtc")
                        .HasDatabaseName("ix_refresh_tokens_used_at_utc");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.HasIndex("FamilyId", "ParentTokenId")
                        .HasDatabaseName("ix_refresh_tokens_family_id_parent_token_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("TarotNow.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActiveTitleRef")
                        .HasColumnType("text")
                        .HasColumnName("active_title_ref");

                    b.Property<string>("AvatarObjectKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("avatar_object_key");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CurrentStreak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("current_streak");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<long>("Exp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("user_exp");

                    b.Property<DateOnly?>("LastStreakDate")
                        .HasColumnType("date")
                        .HasColumnName("last_streak_date");

                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("user_level");

                    b.Property<string>("MfaBackupCodesHashJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("mfa_backup_codes_hash_json");

                    b.Property<bool>("MfaEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("mfa_enabled");

                    b.Property<string>("MfaSecretEncrypted")
                        .HasColumnType("text")
                        .HasColumnName("mfa_secret_encrypted");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<int>("PreBreakStreak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("pre_break_streak");

                    b.Property<string>("ReaderStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("reader_status");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TarotNow.Domain.Entities.UserConsent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ConsentedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consented_at");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("document_type");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_user_consents");

                    b.HasIndex("UserId", "DocumentType", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_user_consents_user_id_document_type_version");

                    b.ToTable("user_consents", (string)null);
                });

            modelBuilder.Entity("TarotNow.Domain.Entities.UserGachaPity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("LastPityResetAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_pity_reset_at_utc");

                    b.Property<Guid>("PoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("pool_id");

                    b.Property<int>("PullCount")
                        .HasColumnType("integer")
                        .HasColumnName("pull_count");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_gacha_pities");

                    b.HasIndex("UserId", "PoolId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_gacha_pities_user_id_pool_id");

                    b.ToTable("user_gacha_pities", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_gacha_pities_pull_count_non_negative", "\"pull_count\" >= 0");
                        });
                });

            modelBuilder.Entity("TarotNow.Domain.Entities.UserItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AcquiredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acquired_at_utc");

                    b.Property<Guid>("ItemDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_definition_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_items");

                    b.HasIndex("ItemDefinitionId")
                        .HasDatabaseName("ix_user_items_item_definition_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_items_user_id");

                    b.HasIndex("UserId", "ItemDefinitionId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_items_user_id_item_definition_id");

                    b.ToTable("user_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_items_quantity_non_negative", "\"quantity\" >= 0");
                        });
                });

            modelBuilder.Entity("TarotNow.Domain.Entities.WalletTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<long>("BalanceAfter")
                        .HasColumnType("bigint")
                        .HasColumnName("balance_after");

                    b.Property<long>("BalanceBefore")
                        .HasColumnType("bigint")
                        .HasColumnName("balance_before");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("IdempotencyKey")
                        .HasColumnType("text")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<string>("ReferenceId")
                        .HasColumnType("text")
                        .HasColumnName("reference_id");

                    b.Property<string>("ReferenceSource")
                        .HasColumnType("text")
                        .HasColumnName("reference_source");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_wallet_transactions");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_wallet_transactions_idempotency_key")
                        .HasFilter("idempotency_key IS NOT NULL");

                    b.ToTable("wallet_transactions", (string)null);
                });

            modelBuilder.Entity("TarotNow.Domain.Entities.WithdrawalRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("admin_id");

                    b.Property<string>("AdminNote")
                        .HasColumnType("text")
                        .HasColumnName("admin_note");

                    b.Property<long>("AmountDiamond")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_diamond");

                    b.Property<long>("AmountVnd")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_vnd");

                    b.Property<string>("BankAccountName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bank_account_name");

                    b.Property<string>("BankAccountNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bank_account_number");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bank_name");

                    b.Property<DateOnly>("BusinessDateUtc")
                        .HasColumnType("date")
                        .HasColumnName("business_date_utc");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("FeeVnd")
                        .HasColumnType("bigint")
                        .HasColumnName("fee_vnd");

                    b.Property<long>("NetAmountVnd")
                        .HasColumnType("bigint")
                        .HasColumnName("net_amount_vnd");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_withdrawal_requests");

                    b.HasIndex("UserId", "BusinessDateUtc")
                        .IsUnique()
                        .HasDatabaseName("ix_withdrawal_one_per_day_active")
                        .HasFilter("status in ('pending','approved')");

                    b.ToTable("withdrawal_requests", (string)null);
                });

            modelBuilder.Entity("TarotNow.Infrastructure.Persistence.Outbox.OutboxHandlerState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("HandlerName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("handler_name");

                    b.Property<Guid>("OutboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_message_id");

                    b.Property<DateTime>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_outbox_handler_states");

                    b.HasIndex("ProcessedAtUtc")
                        .HasDatabaseName("ix_outbox_handler_states_processed_at_utc");

                    b.HasIndex("OutboxMessageId", "HandlerName")
                        .IsUnique()
                        .HasDatabaseName("ux_outbox_handler_states_message_handler");

                    b.ToTable("outbox_handler_states", (string)null);
                });

            modelBuilder.Entity("TarotNow.Infrastructure.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("last_error");

                    b.Property<string>("LockOwner")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("lock_owner");

                    b.Property<DateTime?>("LockedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_at_utc");

                    b.Property<DateTime>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at_utc");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("ix_outbox_messages_occurred_at_utc");

                    b.HasIndex("Status", "NextAttemptAtUtc", "CreatedAtUtc")
                        .HasDatabaseName("ix_outbox_messages_polling");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("TarotNow.Domain.Entities.AiRequest", b =>
                {
                    b.HasOne("TarotNow.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ai_requests_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TarotNow.Domain.Entities.AuthSession", b =>
                {
                    b.HasOne("TarotNow.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auth_sessions_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TarotNow.Domain.Entities.ChatQuestionItem", b =>
                {
                    b.HasOne("TarotNow.Domain.Entities.ChatFinanceSession", "FinanceSession")
                        .WithMany("QuestionItems")
                        .HasForeignKey("FinanceSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_question_items_chat_finance_sessions_finance_session_id");

                    b.Navigation("FinanceSession");
                });

            modelBuilder.Entity("TarotNow.Domain.Entities.DepositOrder", b =>
                {
                    b.HasOne("TarotNow.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deposit_orders_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TarotNow.Domain.Entities.EmailOtp", b =>
                {
                    b.HasOne("TarotNow.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_email_otps_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TarotNow.Domain.Entities.GachaPoolRewardRate", b =>
                {
                    b.HasOne("TarotNow.Domain.Entities.GachaPool", "Pool")
                        .WithMany()
                        .HasForeignKey("PoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_gacha_pool_reward_rates_gacha_pools_pool_id");

                    b.Navigation("Pool");
                });

            modelBuilder.Entity("TarotNow.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("TarotNow.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TarotNow.Domain.Entities.User", b =>
                {
                    b.OwnsOne("TarotNow.Domain.Entities.UserWallet", "Wallet", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<long>("DiamondBalance")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasDefaultValue(0L)
                                .HasColumnName("diamond_balance");

                            b1.Property<long>("FrozenDiamondBalance")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasDefaultValue(0L)
                                .HasColumnName("frozen_diamond_balance");

                            b1.Property<long>("GoldBalance")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasDefaultValue(0L)
                                .HasColumnName("gold_balance");

                            b1.Property<long>("TotalDiamondsPurchased")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasDefaultValue(0L)
                                .HasColumnName("total_diamonds_purchased");

                            b1.HasKey("UserId")
                                .HasName("pk_users");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_users_users_id");
                        });

                    b.Navigation("Wallet")
                        .IsRequired();
                });

            modelBuilder.Entity("TarotNow.Domain.Entities.UserConsent", b =>
                {
                    b.HasOne("TarotNow.Domain.Entities.User", "User")
                        .WithMany("Consents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_consents_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TarotNow.Domain.Entities.UserItem", b =>
                {
                    b.HasOne("TarotNow.Domain.Entities.ItemDefinition", "ItemDefinition")
                        .WithMany()
                        .HasForeignKey("ItemDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_items_item_definitions_item_definition_id");

                    b.Navigation("ItemDefinition");
                });

            modelBuilder.Entity("TarotNow.Infrastructure.Persistence.Outbox.OutboxHandlerState", b =>
                {
                    b.HasOne("TarotNow.Infrastructure.Persistence.Outbox.OutboxMessage", null)
                        .WithMany()
                        .HasForeignKey("OutboxMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_outbox_handler_states_outbox_messages_outbox_message_id");
                });

            modelBuilder.Entity("TarotNow.Domain.Entities.ChatFinanceSession", b =>
                {
                    b.Navigation("QuestionItems");
                });

            modelBuilder.Entity("TarotNow.Domain.Entities.User", b =>
                {
                    b.Navigation("Consents");
                });
#pragma warning restore 612, 618
        }
    }
}
