import { cn } from '@/lib/utils';

export const gachaClientPageClasses = {
  container: cn('container', 'mx-auto', 'flex', 'max-w-5xl', 'flex-col', 'items-center', 'px-4', 'py-8'),
  toolbar: cn('mb-4', 'flex', 'w-full', 'justify-end'),
  hero: cn('mb-12', 'space-y-4', 'text-center'),
  heroTitle: cn(
    'flex',
    'items-center',
    'justify-center',
    'gap-3',
    'bg-gradient-to-r',
    'from-amber-200',
    'via-yellow-400',
    'to-orange-500',
    'bg-clip-text',
    'text-5xl',
    'font-black',
    'text-transparent',
    'drop-shadow-sm',
  ),
  heroIconLeft: cn('h-8', 'w-8', 'text-yellow-400'),
  heroIconRight: cn('h-8', 'w-8', 'text-orange-400'),
  heroSubtitle: cn('mx-auto', 'max-w-xl', 'text-lg', 'text-stone-400'),
  grid: cn('flex', 'w-full', 'flex-wrap', 'justify-center', 'gap-8'),
  loadingCard: cn(
    'flex',
    'h-96',
    'w-full',
    'max-w-md',
    'items-center',
    'justify-center',
    'rounded-3xl',
    'border',
    'border-stone-800',
    'bg-stone-900/50',
    'animate-pulse',
  ),
  loadingText: cn('italic', 'text-stone-600'),
  errorCard: cn(
    'w-full',
    'max-w-2xl',
    'rounded-2xl',
    'border',
    'border-dashed',
    'border-red-900/30',
    'bg-red-950/20',
    'p-12',
    'text-center',
    'text-red-400',
  ),
  errorTitle: cn('mb-2', 'font-bold'),
  errorBody: cn('mb-4', 'text-sm', 'opacity-80'),
  emptyCard: cn(
    'w-full',
    'max-w-2xl',
    'rounded-2xl',
    'border',
    'border-dashed',
    'border-stone-800',
    'p-12',
    'text-center',
    'text-stone-500',
  ),
};
