import { cn } from '@/lib/utils';

export const paymentOfferModalClasses = {
  overlay: cn('fixed', 'inset-0', 'z-50', 'flex', 'items-center', 'justify-center', 'p-4'),
  backdrop: cn('absolute', 'inset-0', 'bg-black/60', 'backdrop-blur-sm'),
  panel: cn(
    'relative',
    'w-full',
    'max-w-md',
    'overflow-hidden',
    'rounded-2xl',
    'border',
    'border-white/10',
    'bg-zinc-900',
    'p-6',
    'shadow-2xl',
    'animate-in',
    'fade-in',
    'zoom-in-95',
    'duration-200',
  ),
  header: cn('mb-6', 'flex', 'items-center', 'justify-between'),
  headerLeft: cn('flex', 'items-center', 'gap-3'),
  iconWrap: cn('flex', 'h-10', 'w-10', 'items-center', 'justify-center', 'rounded-full', 'bg-amber-500/20'),
  title: cn('text-xl', 'font-black', 'italic', 'tracking-tight', 'text-white'),
  closeButton: cn('p-2', 'text-zinc-400', 'transition-colors'),
  form: cn('space-y-4'),
  fieldWrap: cn('space-y-2'),
  label: cn('block', 'text-xs', 'font-bold', 'uppercase', 'tracking-wider', 'text-white'),
  input: cn(
    'w-full',
    'rounded-xl',
    'border',
    'border-white/10',
    'bg-white/5',
    'px-4',
    'py-3',
    'text-white',
    'transition-colors',
    'focus:border-amber-400/50',
    'focus:outline-none',
  ),
  textarea: cn(
    'w-full',
    'resize-none',
    'rounded-xl',
    'border',
    'border-white/10',
    'bg-white/5',
    'px-4',
    'py-3',
    'text-white',
    'transition-colors',
    'focus:border-amber-400/50',
    'focus:outline-none',
  ),
  counter: cn('mt-1', 'text-xs', 'text-zinc-400'),
  submit: cn(
    'mt-4',
    'flex',
    'w-full',
    'items-center',
    'justify-center',
    'gap-2',
    'rounded-xl',
    'bg-amber-500',
    'py-3',
    'font-bold',
    'uppercase',
    'tracking-widest',
    'text-black',
    'transition-colors',
    'disabled:opacity-50',
  ),
};
